### ISSUE TITLE
漏饼

### ISSUE THREAD

**Issue by phidiaLam** [hguandl/dr-feeder#4]
2周年直播期间的饼没有发出来，只有在22点30分收到“出现公告弹窗，可能会有新饼”

**Comment by hguandl** [comment]
可能需要更新版本，用最新版部署的发饼状况是正常的

![IMG_1676](https://user-images.githubusercontent.com/10684225/115982522-79c91780-a5ce-11eb-8b87-5dc07b69f041.JPEG)
![IMG_1675](https://user-images.githubusercontent.com/10684225/115982528-7d5c9e80-a5ce-11eb-9329-c05a6282b8fd.JPEG)

**Comment by phidiaLam** [comment]
好的 之前没出现漏饼的情况 我之前换过一次版本，用的是2.3.1的

**Comment by LisanArknights** [comment]
> 2周年直播期间的饼没有发出来，只有在22点30分收到“出现公告弹窗，可能会有新饼”

你好，我非常需要第一时间蹲到新饼，苦苦寻找相关代码和脚本，找到了这里，发现你在下方的评论。
我想向你寻求帮助，如何在手机上使用作者的代码？因为我对Github几乎一窍不通，如果你能教我的话我会非常感激。
我只能凭借运气连接到Github来，我不能及时回复你，如果你愿意的话，可以一股脑地把你想教我的内容回复给我，谢谢（我正在使用Via浏览器，里面有一个添加脚本的功能）

**Comment by LisanArknights** [comment]
> 可能需要更新版本，用最新版部署的发饼状况是正常的
> 
> ![IMG_1676](https://user-images.githubusercontent.com/10684225/115982522-79c91780-a5ce-11eb-8b87-5dc07b69f041.JPEG)
> ![IMG_1675](https://user-images.githubusercontent.com/10684225/115982528-7d5c9e80-a5ce-11eb-9329-c05a6282b8fd.JPEG)

你好，我非常需要第一时间蹲到新饼，苦苦寻找相关代码和脚本，找到了这里，发现你在下方的评论。
我想向你寻求帮助，如何在手机上使用作者的代码？因为我对Github几乎一窍不通，如果你能教我的话我会非常感激。
我只能凭借运气连接到Github来，我不能及时回复你，如果你愿意的话，可以一股脑地把你想教我的内容回复给我，谢谢（我正在使用Via浏览器，里面有一个添加脚本的功能）
感谢作者的付出～//love

**Comment by phidiaLam** [comment]
> > 2周年直播期间的饼没有发出来，只有在22点30分收到“出现公告弹窗，可能会有新饼”
> 
> 你好，我非常需要第一时间蹲到新饼，苦苦寻找相关代码和脚本，找到了这里，发现你在下方的评论。
> 我想向你寻求帮助，如何在手机上使用作者的代码？因为我对Github几乎一窍不通，如果你能教我的话我会非常感激。
> 我只能凭借运气连接到Github来，我不能及时回复你，如果你愿意的话，可以一股脑地把你想教我的内容回复给我，谢谢（我正在使用Via浏览器，里面有一个添加脚本的功能）

我不是很明白你说的意思，不然你私信我邮箱或者qq我慢慢教你吧

**Comment by LisanArknights** [comment]
> > > 2周年直播期间的饼没有发出来，只有在22点30分收到“出现公告弹窗，可能会有新饼”
> > 
> > 
> > 你好，我非常需要第一时间蹲到新饼，苦苦寻找相关代码和脚本，找到了这里，发现你在下方的评论。
> > 我想向你寻求帮助，如何在手机上使用作者的代码？因为我对Github几乎一窍不通，如果你能教我的话我会非常感激。
> > 我只能凭借运气连接到Github来，我不能及时回复你，如果你愿意的话，可以一股脑地把你想教我的内容回复给我，谢谢（我正在使用Via浏览器，里面有一个添加脚本的功能）
> 
> 我不是很明白你说的意思，不然你私信我邮箱或者qq我慢慢教你吧

我的QQ是：1599435549
谢谢你愿意教我～不好意思，我上面的评论太过语无伦次了（笑哭）
