### ISSUE TITLE
因为接口改变，无法运行

### ISSUE THREAD

**Issue by phidiaLam** [hguandl/dr-feeder#5]
Get "https://ak-fs.hypergryph.com/announce/IOS/announcement.meta.json?sign=1145141919": dial tcp: lookup ak-fs.hypergryph.com: no such host

**Comment by hguandl** [comment]
在 2.3.5 (https://github.com/hguandl/dr-feeder/commit/a7df8b61103087c4f235858727dacab84fbe3357) 里已经更新，但是没有发 release，马上发

**Comment by phidiaLam** [comment]
我直接用你这个分支下的，不过是不是因为没编译还是什么的，运行还是报错旧接口

**Comment by hguandl** [comment]
请再重新编译或者从最新release下载试一下，我这边看代码上已经换掉这个域名了

**Comment by phidiaLam** [comment]
好的

**Comment by phidiaLam** [comment]
隔壁我问的那个开机自启动如果需要我可以帮你写教程

**Comment by phidiaLam** [comment]
我下载的release的source code版本，因为exe好像没办法开机后台自启动，运行还是会报接口错误诶
